host:
port: 8083
storage: cache

credentials:
  api_key: WXsC3dO6ZAF3NgEfz

auth_service:
  url: http://localhost:8082
  api_key: PfS4QVL9dfZEe8RzOAq5Z31Er

users_service:
  url: http://localhost:8081
  api_key: WXsC3dO6ZAF3NgEfz
